// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: none.sql

package store

import (
	"context"
)

const ping = `-- name: Ping :exec
SELECT 1
`

func (q *Queries) Ping(ctx context.Context) error {
	_, err := q.exec(ctx, q.pingStmt, ping)
	return err
}
